

DROP TABLE G_VIDEO;
CREATE TABLE G_VIDEO(
	G_USER_NO NUMBER,
	G_USER_NICKNAME VARCHAR2(100) NOT NULL,
	G_USER_EMAIL VARCHAR2(150) NOT NULL,
	G_USER_PW VARCHAR2(100) NOT NULL,
	G_USER_DATE DATE DEFAULT CURRENT_DATE,
	G_USER_REMOVE CHAR(1) DEFAULT 'N',
	G_USER_PROFILE_IMG VARCHAR2(300),

	
	CONSTRAINT G_USER_PK PRIMARY KEY("G_USER_NO"),
	
	CONSTRAINT "G_USER_REMOVE_CHK"
	CHECK("G_USER_REMOVE" IN ('Y', 'N')));

COMMENT ON COLUMN "G_VIDEO"."G_USER_NO" 					IS '회원 번호 (PK)';
COMMENT ON COLUMN "G_VIDEO"."G_USER_NICKNAME" 		IS '회원 별칭';
COMMENT ON COLUMN "G_VIDEO"."G_USER_EMAIL" 				IS '회원 이메일 (아이디)';
COMMENT ON COLUMN "G_VIDEO"."G_USER_PW" 					IS '회원 비밀번호 ';
COMMENT ON COLUMN "G_VIDEO"."G_USER_DATE" 				IS '가입일 ';
COMMENT ON COLUMN "G_VIDEO"."G_USER_REMOVE" 			IS '탈퇴 여부 ';
COMMENT ON COLUMN "G_VIDEO"."G_USER_PROFILE_IMG" 	IS '프로필 이미지';

CREATE SEQUENCE PK_G_USER_NO NOCACHE;
COMMIT;

SELECT * FROM G_VIDEO;

INSERT INTO "G_VIDEO"
VALUES(PK_G_USER_NO.NEXTVAL, '김성민','sungmin486012@gmail.com', 'tg9415;;',
DEFAULT, DEFAULT,NULL 
	);
	
s
	
