--/*관리자 계정 sys 접속 후 수행*/
--
--
--ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
---- 계정명 원하는 대로 입력 가능.
--
--
--CREATE USER SPRING_KSM IDENTIFIED BY SPRING1234;
---- 계정 생성
--
--GRANT CONNECT, RESOURCE TO SPRING_KSM;
---- 권한 부여
--
--
--ALTER USER SPRING_KSM 
--DEFAULT TABLESPACE USERS
--QUOTA 100M ON USERS;
----테이블 저장 공간 할당



--------------------------------------------------

/*SPRING 계정 접속 후 테이블 생성, 시퀀스 생성*/

/*회원("MEMBER")*/
CREATE TABLE "MEMBER"(
	"MEMBER_NO" 			NUMBER,
	"MEMBER_EMAIL" 		VARCHAR2(50)  NOT NULL,
	"MEMBER_PW" 			VARCHAR2(100) NOT NULL,
	"MEMBER_NICKNAME" NVARCHAR2(10) NOT NULL,
	"MEMBER_TEL"			CHAR(11)      NOT NULL,
	"MEMBER_ADDRESS"	NVARCHAR2(150),
	"PROFILE_IMG"			VARCHAR2(300),
	"ENROLL_DATE"			DATE DEFAULT CURRENT_DATE,
	"MEMBER_DEL_FL"		CHAR(1) DEFAULT 'N',
	"AUTHORITY"				NUMBER DEFAULT 1,
	
	CONSTRAINT "MEMBER_PK" PRIMARY KEY("MEMBER_NO"),
	
	CONSTRAINT "MEMBER_DEL_FL_CHK"
	CHECK("MEMBER_DEL_FL" IN ('Y', 'N')),
	
	CONSTRAINT "AUTHORITY_CHK"
	CHECK("AUTHORITY" IN (1, 2))
);


--COMMENT 추가

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" 				IS '회원번호 (PK)';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" 		IS '회원 이메일 (ID)';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" 				IS '회원 비밀번호 (PK)';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME"  IS '회원명 (별명)';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL"			  IS '회원 전화번호 (-제외)';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" 	IS '회원 주소';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" 			IS '프로필 이미지 경로';
COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" 			IS '가입일';
COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" 		IS '탈퇴 여부(Y,N)';
COMMENT ON COLUMN "MEMBER"."AUTHORITY"			  IS '권한(1:일반, 2:관리자)';

-- 회원 번호 시퀀스 생성

CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

--샘플 회원 데이터 삽입
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'member01@kh.or.kr', 'pass01!',
	  '샘플1', '01012341234', NULL, NULL,
	   DEFAULT, DEFAULT, DEFAULT);
	  
COMMIT;

SELECT * FROM MEMBER;


-- 샘플 데이터 비밀번호 암호화 적용
UPDATE "MEMBER" 
SET 
	"MEMBER_PW" = '$2a$10$b2OsQalO5r3ymQV4jHTKWeZMHlVDJJ2JNzfclufSZHjhzjbpCPDH.'
WHERE 
	"MEMBER_NO" = 1;

COMMIT;

SELECT * FROM MEMBER;



INSERT INTO "MEMBER"
VALUES(
	SEQ_MEMBER_NO.NEXTVAL, 
	'member02@kh.or.kr', 
	'$2a$10$KzFKEvO4C65xBTetZDV8QufZvhQnIGU0SE5ZEaZo0T9SrdYS5oFMC',
	 '샘플2', 
	 '01022222222', 
	 NULL, NULL, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "MEMBER"
VALUES(
	SEQ_MEMBER_NO.NEXTVAL, 
	'member03@kh.or.kr', 
	'$2a$10$KzFKEvO4C65xBTetZDV8QufZvhQnIGU0SE5ZEaZo0T9SrdYS5oFMC',
	 '샘플3', 
	 '01033333333', 
	 NULL, NULL, DEFAULT, DEFAULT, DEFAULT);

SELECT * FROM "MEMBER";

ROLLBACK;

  SELECT
  	COUNT(*)
  FROM
  	"MEMBER"
  WHERE
  	MEMBER_EMAIL = 'member01@kh.or.kr'
  AND
  	MEMBER_DEL_FL = 'N';

  
  UPDATE "MEMBER" 
SET 
	MEMBER_DEL_FL = DECODE(MEMBER_DEL_FL, 'Y','N','Y')
WHERE 
	"MEMBER_NO" = 1;

SELECT * FROM "MEMBER";


COMMIT;

--파일 업로드 테시트용 테이블

CREATE TABLE TB_FILE_TEST(
	FILE_NO NUMBER PRIMARY KEY,
	FILE_ORIGINAL_NAME VARCHAR2(300), -- 원본 파일명
	FILE_RENAME VARCHAR(300), 				-- 변경된 파일명
	FILE_PATH VARCHAR2(300),					-- 파일이 저장된 폴더명
	UPLOAD_DATE DATE DEFAULT CURRENT_DATE	-- 저장된 날짜
);


CREATE SEQUENCE SEQ_FILE_NO NOCACHE; -- 시퀀스 생성

SELECT * FROM TB_FILE_TEST;
COMMIT;


UPDATE TB_FILE_TEST
SET FILE_PATH = '/images/test/';

---------------------------------------------

-- 검색 조건이 일치하는 게시글 수 조회
SELECT COUNT(*)
FROM "BOARD"
JOIN "MEMBER" USING("MEMBER_NO") -- 작성자 검색
WHERE BOARD_CODE = 1
AND BOARD_DEL_FL = 'N'
-- 제목 검색인 경우
--AND BOARD_TITLE LIKE '%' || '11' || '%';

-- 내용 검색인 경우
--AND BOARD_CONTENT LIKE '%' || '11' || '%';

-- 제목 또는 내용 검색
--AND (BOARD_TITLE LIKE '%' || '11' || '%'
--OR BOARD_CONTENT LIKE '%' || '11' || '%');

-- 작성자 검색
AND MEMBER_NICKNAME LIKE  '%' || '11' || '%';

---------------------------------------------------------------
/*현재 게시글이 속해잇는 페이지 번호 조회*/

SELECT 
	RNUM,
	BOARD_NO,
	CEIL(RNUM/10) CP
FROM
	(SELECT
		ROW_NUMBER() OVER(ORDER BY BOARD_NO DESC) RNUM,
		BOARD_NO
	FROM 
		BOARD
	WHERE
		BOARD_CODE = 1
	AND 
		BOARD_DEL_FL = 'N'
	AND
		BOARD_TITLE LIKE '%' || '11' || '%')
WHERE
	BOARD_NO = 2005;


-----------------------------------------------------
/* 현재 게시글이 속해있는 페이지 번호 조회 */
SELECT RNUM, BOARD_NO, CEIL(RNUM/10) CP
FROM
	(SELECT 
		ROW_NUMBER() OVER(ORDER BY BOARD_NO DESC) RNUM
		,BOARD_NO
	FROM "BOARD"
	JOIN "MEMBER" USING(MEMBER_NO)
	WHERE BOARD_CODE = 1
	AND   BOARD_DEL_FL = 'N'
	
--AND   BOARD_TITLE LIKE '%' || '11' || '%'
--AND   BOARD_CONTENT LIKE '%' || '11' || '%'
--	AND   
--		(BOARD_TITLE LIKE '%' || '11' || '%'
--		 OR 
--		 BOARD_CONTENT LIKE '%' || '11' || '%')

	AND MEMBER_NICKNAME LIKE '%' || '윈' || '%'
	)
WHERE BOARD_NO = 1154;






-------------------------------------------------------------------
-------------------------------------------------------------------
/* 알림 테이블 */
CREATE TABLE "NOTIFICATION" (
   "NOTIFICATION_NO"   NUMBER      NOT NULL,
   "NOTIFICATION_CONTENT"   VARCHAR2(1000)      NOT NULL,
   "NOTIFICATION_CHECK"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "NOTIFICATION_DATE"   DATE   DEFAULT CURRENT_DATE   NOT NULL,
   "NOTIFICATION_URL"   VARCHAR2(1000)      NOT NULL,
   "SEND_MEMBER_NO"   NUMBER      NOT NULL,
   "RECEIVE_MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_NO" IS '알림 번호';
COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_CONTENT" IS '알림 내용(HTML 포함)';
COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_CHECK" IS '읽음 여부(Y,N)';
COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_DATE" IS '알림 생성 시간';
COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_URL" IS '연결 페이지 주소';
COMMENT ON COLUMN "NOTIFICATION"."SEND_MEMBER_NO" IS '알림 보낸 회원 번호';
COMMENT ON COLUMN "NOTIFICATION"."RECEIVE_MEMBER_NO" IS '알림 받는 회원 번호';


ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY (
   "NOTIFICATION_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_1" FOREIGN KEY (
   "SEND_MEMBER_NO"
);
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_2" FOREIGN KEY (
   "RECEIVE_MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);


-- 알림 번호 시퀀스 생성
CREATE SEQUENCE SEQ_NOTI_NO NOCACHE;


SELECT * FROM NOTIFICATION;

      SELECT 
         NOTIFICATION_NO, 
         NOTIFICATION_CONTENT, 
         NOTIFICATION_URL, 
         PROFILE_IMG AS SEND_MEMBER_PROFILE_IMG, 
         SEND_MEMBER_NO, 
         RECEIVE_MEMBER_NO,
         NOTIFICATION_CHECK,
         CASE 
            WHEN TRUNC(NOTIFICATION_DATE) = TRUNC(CURRENT_DATE) THEN TO_CHAR(NOTIFICATION_DATE, 'AM HH:MI')
            ELSE TO_CHAR(NOTIFICATION_DATE, 'YYYY-MM-DD')
         END AS NOTIFICATION_DATE
      FROM "NOTIFICATION"
      JOIN "MEMBER" ON (SEND_MEMBER_NO = MEMBER_NO)
      WHERE RECEIVE_MEMBER_NO = 1
      ORDER BY NOTIFICATION_NO DESC;



 SELECT 
 	COUNT(*)
 FROM 
 		NOTIFICATION
	WHERE 
		RECEIVE_MEMBER_NO = 1
	AND
		NOTIFICATION_CHECK = 'N'
	;

SELECT * FROM "MEMBER";

-- SUBSTR(컬럼명, 시작인덱스) : 인덱스 부터 끝까지 잘라서 반환
-- INSTR(컬럼명, '찾을문자열' 검색 순서)

-- INSTR -1 == 뒤에서 부터 찾기


SELECT 
	SUBSTR(PROFILE_IMG,
		INSTR(PROFILE_IMG, '/', -1) +1) AS "FILE_NAME"
FROM 
	"MEMBER"
WHERE
	PROFILE_IMG IS NOT NULL

UNION

SELECT TO_CHAR(IMG_RENAME) "FILE_NAME"
FROM BOARD_IMG;


SELECT
*
FROM
	CHATTING_ROOM;


/*로그인한 회원이 참여한 채팅방 목록 조회*/

		SELECT CHATTING_ROOM_NO
			,(SELECT MESSAGE_CONTENT FROM (
				SELECT * FROM MESSAGE M2
				WHERE M2.CHATTING_ROOM_NO = R.CHATTING_ROOM_NO
				ORDER BY MESSAGE_NO DESC) 
				WHERE ROWNUM = 1) LAST_MESSAGE
			,TO_CHAR(NVL((SELECT MAX(SEND_TIME) SEND_TIME 
					FROM MESSAGE M
					WHERE R.CHATTING_ROOM_NO  = M.CHATTING_ROOM_NO), CREATE_DATE), 
					'YYYY.MM.DD') SEND_TIME
			,NVL2((SELECT OPEN_MEMBER FROM CHATTING_ROOM R2
				WHERE R2.CHATTING_ROOM_NO = R.CHATTING_ROOM_NO
				AND R2.OPEN_MEMBER = 4),
				R.PARTICIPANT,
				R.OPEN_MEMBER
				) TARGET_NO	
			,NVL2((SELECT OPEN_MEMBER FROM CHATTING_ROOM R2
				WHERE R2.CHATTING_ROOM_NO = R.CHATTING_ROOM_NO
				AND R2.OPEN_MEMBER = 4),
				(SELECT MEMBER_NICKNAME FROM MEMBER WHERE MEMBER_NO = R.PARTICIPANT),
				(SELECT MEMBER_NICKNAME FROM MEMBER WHERE MEMBER_NO = R.OPEN_MEMBER)
				) TARGET_NICKNAME	
			,NVL2((SELECT OPEN_MEMBER FROM CHATTING_ROOM R2
				WHERE R2.CHATTING_ROOM_NO = R.CHATTING_ROOM_NO
				AND R2.OPEN_MEMBER = 4),
				(SELECT PROFILE_IMG FROM MEMBER WHERE MEMBER_NO = R.PARTICIPANT),
				(SELECT PROFILE_IMG FROM MEMBER WHERE MEMBER_NO = R.OPEN_MEMBER)
				) TARGET_PROFILE
			,(SELECT COUNT(*) FROM MESSAGE M WHERE M.CHATTING_ROOM_NO = R.CHATTING_ROOM_NO AND READ_FL = 'N' AND SENDER_NO != 4) NOT_READ_COUNT
			,(SELECT MAX(MESSAGE_NO) SEND_TIME FROM MESSAGE M WHERE R.CHATTING_ROOM_NO  = M.CHATTING_ROOM_NO) MAX_MESSAGE_NO
		FROM CHATTING_ROOM R
		WHERE OPEN_MEMBER = 4
		OR PARTICIPANT = 4
		ORDER BY MAX_MESSAGE_NO DESC NULLS LAST




