

CREATE TABLE
	TODOLIST(
		TITLE CHAR(1BYTE) PRIMARY KEY,
		DETAIL VARCHAR2(300BYTE),
		COMPLETE CHAR (1BYTE),
		REGDATE DATE DEFAULT CURRENT_DATE
	);
	
INSERT INTO TODOLIST
VALUES(1,'수학 공부', 'F', '2024,09,02');


INSERT INTO TODOLIST
VALUES(2,'영어공부', 'T', '2024,09,01');

SELECT * FROM TODOLIST;