SELECT
	CLASS_NAME,
	PROFESSOR_NAME
FROM
	TB_CLASS C JOIN TB_PROFESSOR P ON(C.DEPARTMENT_NO = P.DEPARTMENT_NO)
	JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회'
ORDER BY PROFESSOR_NAME ASC;


SELECT * FROM TB_DEPARTMENT;