SELECT
	STUDENT_NO 학번,
	STUDENT_NAME "학생 이름",
	ROUND(POINT,1) "전체 평점"
FROM
	TB_STUDENT  JOIN TB_GRADE USING (STUDENT_NO)
	JOIN TB_DEPARTMENT  USING(DEPARTMENT_NO)
WHERE 
	DEPARTMENT_NAME = '음악학과';



SELECT * FROM TB_STUDENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_DEPARTMENT;