SELECT
	STUDENT_NO,
	STUDENT_NAME,
	DEPARTMENT_NAME
FROM
	TB_STUDENT S JOIN TB_DEPARTMENT D ON
	(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY 	STUDENT_NAME ASC;

	
	
	
	
	SELECT * FROM TB_DEPARTMENT;
	SELECT * FROM TB_CLASS;
	SELECT * FROM TB_STUDENT;
	