-- MEMBERS 테이블 생성

CREATE TABLE MEMBERS(

MEMBER_ID VARCHAR2(20) ,

MEMBER_PWD VARCHAR2(20) NOT NULL,

/*MEMBER_NAME CHAR(30)*/ MEMBER_NAME VARCHAR(30), -- 가변길이인 VARCHAR 사용

MEMBER_AGE NUMBER,

MEMBER_EMAIL VARCHAR2(50),

PRIMARY KEY(MEMBER_ID)

);
SELECT * FROM MEMBERS;


-- BOARDS 테이블 생성
DROP TABLE BOARDS;
CREATE TABLE BOARDS(

BOARD_NO NUMBER PRIMARY KEY,

BOARD_TITLE VARCHAR2(100),

BOARD_CONTENT VARCHAR2(4000),

BOARD_WRITER VARCHAR2(20) ,

/*BOARD_REG_DATE DATE DEFAULT '2023-03-22'*/
BOARD_REG_DATE DATE DEFAULT CURRENT_DATE

,FOREIGN KEY(BOARD_WRITER)REFERENCES MEMBERS(MEMBER_ID)
--FOREIGN KEY(컬럼명) REFERENCES 참조 테이블명(참조컬럼명)
);

SELECT * FROM BOARDS;